version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: packeteye-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: packeteye
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: packeteye-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/packeteye?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  ml-service:
    build: ./mlmodel
    container_name: packeteye-ml
    ports:
      - "8001:8001"
    environment:
      - PORT=8001

volumes:
  db_data:
